/**
 * In-memory demo dataset.
 *
 * Stands in for the Postgres layer described in PRD §3 so the console is
 * navigable before the FastAPI backend exists. Every shape here matches
 * `types.ts` exactly, so swapping this module for real queries is a change of
 * implementation, not of contract.
 *
 * Dates are anchored to a fixed instant so the demo renders identically on
 * every machine and in CI.
 */

import type {
  AgentRun,
  AuditEvent,
  BusinessRules,
  Call,
  Driver,
  Load,
  Negotiation,
  Tenant,
  Truck,
  User,
} from "./types";

/** Everything in the dataset is relative to this instant. */
export const NOW = new Date("2026-08-17T14:00:00Z");

const hours = (n: number) => new Date(NOW.getTime() + n * 3_600_000).toISOString();

export const tenant: Tenant = {
  id: "t_1",
  name: "Redline Carriers LLC",
  plan: "pilot",
  concurrentCallLimit: 3,
  approvedCallingRegions: ["US-TX", "US-OK", "US-NM", "US-AR", "US-LA", "US-TN", "US-GA"],
  recordingPolicy: "all_parties_consent",
};

export const currentUser: User = {
  id: "u_1",
  tenantId: "t_1",
  name: "Yahya Ameer",
  email: "yahyeameer44@gmail.com",
  role: "admin",
};

export const businessRules: BusinessRules = {
  tenantId: "t_1",
  maxRatePercentOfBroker: 82,
  maxRateAbsolute: 3200,
  autoApproveCounterThreshold: 75,
  callWindowStartHour: 8,
  callWindowEndHour: 20,
  maxCallAttemptsPerDriverPerLoad: 2,
  minOutcomeConfidence: 0.75,
  autonomousCallingEnabled: true,
};

export const drivers: Driver[] = [
  {
    id: "d_1",
    tenantId: "t_1",
    name: "Marcus Webb",
    phone: "+1 214 555 0142",
    homeBase: "Dallas, TX",
    currentLocation: "Fort Worth, TX",
    currentLat: 32.7555,
    currentLng: -97.3308,
    equipment: ["dry_van", "reefer"],
    status: "available",
    availableFrom: hours(-6),
    preferences: ["Texas", "Oklahoma"],
    avoids: ["Colorado"],
    notes: "Prefers to be home by Friday night. Reliable on morning pickups.",
    acceptanceRate: 0.72,
  },
  {
    id: "d_2",
    tenantId: "t_1",
    name: "Deante Rollins",
    phone: "+1 918 555 0177",
    homeBase: "Tulsa, OK",
    currentLocation: "Oklahoma City, OK",
    currentLat: 35.4676,
    currentLng: -97.5164,
    equipment: ["dry_van"],
    status: "available",
    availableFrom: hours(2),
    preferences: ["Oklahoma", "Kansas"],
    avoids: [],
    notes: "Newer to the fleet. Ask twice on appointment times.",
    acceptanceRate: 0.55,
  },
  {
    id: "d_3",
    tenantId: "t_1",
    name: "Ana Sotelo",
    phone: "+1 505 555 0119",
    homeBase: "Albuquerque, NM",
    currentLocation: "Amarillo, TX",
    currentLat: 35.222,
    currentLng: -101.8313,
    equipment: ["reefer", "dry_van"],
    status: "available",
    availableFrom: hours(-1),
    preferences: ["New Mexico", "Arizona"],
    avoids: [],
    notes: "Strongest reefer driver. Will negotiate hard on long deadhead.",
    acceptanceRate: 0.81,
  },
  {
    id: "d_4",
    tenantId: "t_1",
    name: "Tommy Nguyen",
    phone: "+1 713 555 0163",
    homeBase: "Houston, TX",
    currentLocation: "Houston, TX",
    currentLat: 29.7604,
    currentLng: -95.3698,
    equipment: ["flatbed", "step_deck"],
    status: "available",
    availableFrom: hours(4),
    preferences: ["Louisiana", "Texas"],
    avoids: [],
    notes: "Flatbed and step deck only. Very responsive by phone.",
    acceptanceRate: 0.68,
  },
  {
    id: "d_5",
    tenantId: "t_1",
    name: "Rashid Baker",
    phone: "+1 901 555 0188",
    homeBase: "Memphis, TN",
    currentLocation: "Little Rock, AR",
    currentLat: 34.7465,
    currentLng: -92.2896,
    equipment: ["dry_van"],
    status: "on_load",
    availableFrom: hours(30),
    preferences: ["Tennessee", "Georgia"],
    avoids: [],
    notes: "Delivering in Nashville, empty Tuesday morning.",
    acceptanceRate: 0.77,
  },
  {
    id: "d_6",
    tenantId: "t_1",
    name: "Grace Okafor",
    phone: "+1 404 555 0134",
    homeBase: "Atlanta, GA",
    currentLocation: "Atlanta, GA",
    currentLat: 33.749,
    currentLng: -84.388,
    equipment: ["reefer"],
    status: "available",
    availableFrom: hours(1),
    preferences: ["Georgia", "Florida"],
    avoids: ["Texas"],
    notes: "Reefer specialist. Has asked not to be routed west of Louisiana.",
    acceptanceRate: 0.9,
  },
  {
    id: "d_7",
    tenantId: "t_1",
    name: "Bill Hartley",
    phone: "+1 214 555 0198",
    homeBase: "Dallas, TX",
    currentLocation: "Dallas, TX",
    currentLat: 32.7767,
    currentLng: -96.797,
    equipment: ["dry_van", "flatbed"],
    status: "do_not_call",
    availableFrom: hours(0),
    preferences: ["Texas"],
    avoids: [],
    notes: "Asked to be contacted by text only. Do not place AI calls.",
    acceptanceRate: 0.4,
  },
  {
    id: "d_8",
    tenantId: "t_1",
    name: "Sofia Marchetti",
    phone: "+1 504 555 0155",
    homeBase: "New Orleans, LA",
    currentLocation: "Baton Rouge, LA",
    currentLat: 30.4515,
    currentLng: -91.1871,
    equipment: ["tanker", "dry_van"],
    status: "available",
    availableFrom: hours(-3),
    preferences: ["Louisiana", "Mississippi"],
    avoids: [],
    notes: "Tanker endorsed. Prefers short runs close to home.",
    acceptanceRate: 0.63,
  },
];

export const trucks: Truck[] = [
  { id: "tr_1", tenantId: "t_1", unitNumber: "104", type: "dry_van", capacityLbs: 45000, driverId: "d_1" },
  { id: "tr_2", tenantId: "t_1", unitNumber: "112", type: "dry_van", capacityLbs: 45000, driverId: "d_2" },
  { id: "tr_3", tenantId: "t_1", unitNumber: "118", type: "reefer", capacityLbs: 43000, driverId: "d_3" },
  { id: "tr_4", tenantId: "t_1", unitNumber: "121", type: "flatbed", capacityLbs: 48000, driverId: "d_4" },
  { id: "tr_5", tenantId: "t_1", unitNumber: "127", type: "dry_van", capacityLbs: 45000, driverId: "d_5" },
  { id: "tr_6", tenantId: "t_1", unitNumber: "133", type: "reefer", capacityLbs: 43000, driverId: "d_6" },
  { id: "tr_7", tenantId: "t_1", unitNumber: "140", type: "tanker", capacityLbs: 42000, driverId: "d_8" },
];

export const loads: Load[] = [
  {
    id: "l_1",
    tenantId: "t_1",
    reference: "RL-4471",
    origin: "Dallas, TX",
    originLat: 32.7767,
    originLng: -96.797,
    destination: "Houston, TX",
    destinationLat: 29.7604,
    destinationLng: -95.3698,
    miles: 239,
    pickupWindowStart: hours(18),
    pickupWindowEnd: hours(26),
    deliveryWindowStart: hours(30),
    deliveryWindowEnd: hours(38),
    equipment: "dry_van",
    commodity: "Packaged food",
    weightLbs: 38000,
    brokerRate: 1150,
    authorizedRate: 900,
    brokerName: "Cardinal Logistics",
    brokerContact: "+1 469 555 0100",
    status: "pending_approval",
    assignedDriverId: null,
    createdAt: hours(-4),
  },
  {
    id: "l_2",
    tenantId: "t_1",
    reference: "RL-4472",
    origin: "Amarillo, TX",
    originLat: 35.222,
    originLng: -101.8313,
    destination: "Albuquerque, NM",
    destinationLat: 35.0844,
    destinationLng: -106.6504,
    miles: 288,
    pickupWindowStart: hours(12),
    pickupWindowEnd: hours(20),
    deliveryWindowStart: hours(26),
    deliveryWindowEnd: hours(34),
    equipment: "reefer",
    commodity: "Fresh produce",
    weightLbs: 41000,
    brokerRate: 1620,
    authorizedRate: 1300,
    brokerName: "Sunbelt Freight",
    brokerContact: "+1 806 555 0121",
    status: "calling",
    assignedDriverId: null,
    createdAt: hours(-2),
  },
  {
    id: "l_3",
    tenantId: "t_1",
    reference: "RL-4473",
    origin: "Houston, TX",
    originLat: 29.7604,
    originLng: -95.3698,
    destination: "Baton Rouge, LA",
    destinationLat: 30.4515,
    destinationLng: -91.1871,
    miles: 271,
    pickupWindowStart: hours(20),
    pickupWindowEnd: hours(28),
    deliveryWindowStart: hours(32),
    deliveryWindowEnd: hours(40),
    equipment: "flatbed",
    commodity: "Steel coil",
    weightLbs: 46000,
    brokerRate: 1480,
    authorizedRate: 1150,
    brokerName: "Gulf Coast Brokerage",
    brokerContact: "+1 713 555 0144",
    status: "needs_driver",
    assignedDriverId: null,
    createdAt: hours(-1),
  },
  {
    id: "l_4",
    tenantId: "t_1",
    reference: "RL-4469",
    origin: "Oklahoma City, OK",
    originLat: 35.4676,
    originLng: -97.5164,
    destination: "Tulsa, OK",
    destinationLat: 36.154,
    destinationLng: -95.9928,
    miles: 106,
    pickupWindowStart: hours(-20),
    pickupWindowEnd: hours(-14),
    deliveryWindowStart: hours(-10),
    deliveryWindowEnd: hours(-4),
    equipment: "dry_van",
    commodity: "Retail goods",
    weightLbs: 22000,
    brokerRate: 620,
    authorizedRate: 480,
    brokerName: "Cardinal Logistics",
    brokerContact: "+1 469 555 0100",
    status: "delivered",
    assignedDriverId: "d_2",
    createdAt: hours(-48),
  },
  {
    id: "l_5",
    tenantId: "t_1",
    reference: "RL-4470",
    origin: "Atlanta, GA",
    originLat: 33.749,
    originLng: -84.388,
    destination: "Nashville, TN",
    destinationLat: 36.1627,
    destinationLng: -86.7816,
    miles: 250,
    pickupWindowStart: hours(-6),
    pickupWindowEnd: hours(2),
    deliveryWindowStart: hours(8),
    deliveryWindowEnd: hours(16),
    equipment: "reefer",
    commodity: "Dairy",
    weightLbs: 39000,
    brokerRate: 1390,
    authorizedRate: 1100,
    brokerName: "Peachtree Transport",
    brokerContact: "+1 404 555 0166",
    status: "in_transit",
    assignedDriverId: "d_6",
    createdAt: hours(-26),
  },
  {
    id: "l_6",
    tenantId: "t_1",
    reference: "RL-4474",
    origin: "Baton Rouge, LA",
    originLat: 30.4515,
    originLng: -91.1871,
    destination: "Memphis, TN",
    destinationLat: 35.1495,
    destinationLng: -90.049,
    miles: 396,
    pickupWindowStart: hours(30),
    pickupWindowEnd: hours(40),
    deliveryWindowStart: hours(46),
    deliveryWindowEnd: hours(56),
    equipment: "dry_van",
    commodity: "Paper products",
    weightLbs: 34000,
    brokerRate: 1740,
    authorizedRate: 1400,
    brokerName: "Delta Freight Partners",
    brokerContact: "+1 901 555 0132",
    status: "needs_driver",
    assignedDriverId: null,
    createdAt: hours(0),
  },
  {
    id: "l_7",
    tenantId: "t_1",
    reference: "RL-4475",
    origin: "Fort Worth, TX",
    originLat: 32.7555,
    originLng: -97.3308,
    destination: "Little Rock, AR",
    destinationLat: 34.7465,
    destinationLng: -92.2896,
    miles: 353,
    pickupWindowStart: hours(24),
    pickupWindowEnd: hours(34),
    deliveryWindowStart: hours(40),
    deliveryWindowEnd: hours(50),
    equipment: "dry_van",
    commodity: "Building materials",
    weightLbs: 40000,
    brokerRate: 1560,
    authorizedRate: 1250,
    brokerName: "Sunbelt Freight",
    brokerContact: "+1 806 555 0121",
    status: "draft",
    assignedDriverId: null,
    createdAt: hours(0),
  },
];

export const calls: Call[] = [
  {
    id: "c_1",
    tenantId: "t_1",
    loadId: "l_1",
    driverId: "d_1",
    direction: "outbound",
    phone: "+1 214 555 0142",
    providerCallId: "vapi_8f31a2",
    startedAt: hours(-3),
    durationSeconds: 96,
    outcome: "counteroffer",
    outcomeConfidence: 0.93,
    counterofferAmount: 975,
    costUsd: 0.21,
    avgResponseLatencyMs: 1180,
    recordingUrl: "/recordings/c_1.mp3",
    transcript: [
      { speaker: "system", at: 0, text: "Call connected. Consent preamble played." },
      {
        speaker: "agent",
        at: 3,
        text: "Hi Marcus, this is the dispatch assistant at Redline Carriers. This call is recorded. Do you have thirty seconds?",
      },
      { speaker: "driver", at: 9, text: "Yeah, go ahead." },
      {
        speaker: "agent",
        at: 11,
        text: "I have a dry van load, Dallas to Houston, 239 miles. Pickup tomorrow between eight in the morning and four in the afternoon. Packaged food, 38,000 pounds. It pays 900 to you. Are you interested?",
      },
      { speaker: "driver", at: 24, text: "Dallas to Houston... what time does it deliver?" },
      {
        speaker: "agent",
        at: 28,
        text: "Delivery window is the following morning, eight to four. You would be empty in Houston by mid afternoon.",
      },
      { speaker: "driver", at: 36, text: "I can do it but not for nine. Make it 975 and I'll take it." },
      {
        speaker: "agent",
        at: 43,
        text: "Let me read that back — 975 dollars, Dallas to Houston, picking up tomorrow morning. Is that right?",
      },
      { speaker: "driver", at: 50, text: "That's right." },
      {
        speaker: "agent",
        at: 52,
        text: "975 is above what I'm authorized to agree to, so I'm sending it to a dispatcher now. You'll hear back within the hour. Thanks Marcus.",
      },
      { speaker: "driver", at: 61, text: "Sounds good." },
      {
        speaker: "system",
        at: 64,
        text: "Outcome extracted: counteroffer, $975, confidence 0.93. Authorization check returned human_approval_required.",
      },
    ],
  },
  {
    id: "c_2",
    tenantId: "t_1",
    loadId: "l_2",
    driverId: "d_3",
    direction: "outbound",
    phone: "+1 505 555 0119",
    providerCallId: "vapi_9c02b7",
    startedAt: hours(-1),
    durationSeconds: 71,
    outcome: "interested",
    outcomeConfidence: 0.96,
    counterofferAmount: null,
    costUsd: 0.16,
    avgResponseLatencyMs: 940,
    recordingUrl: "/recordings/c_2.mp3",
    transcript: [
      { speaker: "system", at: 0, text: "Call connected. Consent preamble played." },
      {
        speaker: "agent",
        at: 3,
        text: "Hi Ana, dispatch assistant at Redline Carriers, this call is recorded. I have a reefer load out of Amarillo.",
      },
      { speaker: "driver", at: 9, text: "I'm in Amarillo right now. Where's it going?" },
      {
        speaker: "agent",
        at: 12,
        text: "Albuquerque, 288 miles, fresh produce, 41,000 pounds. Pickup today between two and ten at night. It pays 1,300.",
      },
      { speaker: "driver", at: 22, text: "That works. I'm empty already." },
      {
        speaker: "agent",
        at: 25,
        text: "Great. Confirming: 1,300 dollars, Amarillo to Albuquerque, pickup tonight. I'll send the rate confirmation by text.",
      },
      { speaker: "driver", at: 34, text: "Perfect." },
      {
        speaker: "system",
        at: 37,
        text: "Outcome extracted: interested, confidence 0.96. Within authorization; load moved to assigned.",
      },
    ],
  },
  {
    id: "c_3",
    tenantId: "t_1",
    loadId: "l_2",
    driverId: "d_2",
    direction: "outbound",
    phone: "+1 918 555 0177",
    providerCallId: "vapi_1a77d4",
    startedAt: hours(-2),
    durationSeconds: 34,
    outcome: "rejected",
    outcomeConfidence: 0.89,
    counterofferAmount: null,
    costUsd: 0.08,
    avgResponseLatencyMs: 1320,
    recordingUrl: "/recordings/c_3.mp3",
    transcript: [
      { speaker: "system", at: 0, text: "Call connected. Consent preamble played." },
      {
        speaker: "agent",
        at: 3,
        text: "Hi Deante, dispatch assistant at Redline Carriers, recorded line. I have a reefer load from Amarillo to Albuquerque.",
      },
      { speaker: "driver", at: 10, text: "I don't have a reefer, I'm van only." },
      {
        speaker: "agent",
        at: 14,
        text: "Understood, I'll note that and won't send you reefer loads. Thanks Deante.",
      },
      {
        speaker: "system",
        at: 19,
        text: "Outcome extracted: rejected (equipment mismatch), confidence 0.89. Driver equipment profile flagged for review.",
      },
    ],
  },
  {
    id: "c_4",
    tenantId: "t_1",
    loadId: "l_3",
    driverId: "d_4",
    direction: "outbound",
    phone: "+1 713 555 0163",
    providerCallId: "vapi_44e1c9",
    startedAt: hours(-0.5),
    durationSeconds: 18,
    outcome: "no_answer",
    outcomeConfidence: 1,
    counterofferAmount: null,
    costUsd: 0.03,
    avgResponseLatencyMs: 0,
    recordingUrl: null,
    transcript: [
      { speaker: "system", at: 0, text: "Dialing +1 713 555 0163." },
      { speaker: "system", at: 18, text: "No answer after 18 seconds. Retry scheduled in 45 minutes." },
    ],
  },
  {
    id: "c_5",
    tenantId: "t_1",
    loadId: "l_6",
    driverId: "d_8",
    direction: "outbound",
    phone: "+1 504 555 0155",
    providerCallId: "vapi_7b93f0",
    startedAt: hours(-0.2),
    durationSeconds: 58,
    outcome: "callback_requested",
    outcomeConfidence: 0.68,
    counterofferAmount: null,
    costUsd: 0.13,
    avgResponseLatencyMs: 1490,
    recordingUrl: "/recordings/c_5.mp3",
    transcript: [
      { speaker: "system", at: 0, text: "Call connected. Consent preamble played." },
      {
        speaker: "agent",
        at: 3,
        text: "Hi Sofia, dispatch assistant at Redline Carriers, recorded line. I have a dry van run from Baton Rouge to Memphis.",
      },
      { speaker: "driver", at: 11, text: "[crosstalk] ...driving right now, can you — [inaudible]" },
      { speaker: "agent", at: 16, text: "No problem. When is a better time to reach you?" },
      { speaker: "driver", at: 20, text: "Try me after [inaudible] tonight." },
      {
        speaker: "agent",
        at: 26,
        text: "I'll call back this evening. Drive safe, Sofia.",
      },
      {
        speaker: "system",
        at: 31,
        text: "Outcome extracted: callback_requested, confidence 0.68 — below the 0.75 threshold. Escalated to a dispatcher to set the callback time manually.",
      },
    ],
  },
  {
    id: "c_6",
    tenantId: "t_1",
    loadId: "l_5",
    driverId: "d_6",
    direction: "outbound",
    phone: "+1 404 555 0134",
    providerCallId: "vapi_2d55aa",
    startedAt: hours(-25),
    durationSeconds: 63,
    outcome: "interested",
    outcomeConfidence: 0.94,
    counterofferAmount: null,
    costUsd: 0.15,
    avgResponseLatencyMs: 1020,
    recordingUrl: "/recordings/c_6.mp3",
    transcript: [
      { speaker: "system", at: 0, text: "Call connected. Consent preamble played." },
      {
        speaker: "agent",
        at: 3,
        text: "Hi Grace, dispatch assistant at Redline Carriers, recorded line. Reefer load, Atlanta to Nashville, dairy, 250 miles, pays 1,100.",
      },
      { speaker: "driver", at: 14, text: "Yeah I'll take that one. Same dock as last time?" },
      { speaker: "agent", at: 19, text: "Same consignee, yes. Pickup window opens in two hours." },
      { speaker: "driver", at: 24, text: "I'll head over." },
      { speaker: "system", at: 27, text: "Outcome extracted: interested, confidence 0.94. Load assigned." },
    ],
  },
];

export const negotiations: Negotiation[] = [
  {
    id: "n_1",
    tenantId: "t_1",
    loadId: "l_1",
    driverId: "d_1",
    callId: "c_1",
    offeredRate: 900,
    counterRate: 975,
    authorizationCeiling: 900,
    status: "pending",
    reason: "$975 is $75 over our offer and above the rate authorized on this load ($900).",
    createdAt: hours(-3),
    decidedAt: null,
    decidedByUserId: null,
  },
  {
    id: "n_2",
    tenantId: "t_1",
    loadId: "l_6",
    driverId: "d_8",
    callId: "c_5",
    offeredRate: 1400,
    counterRate: 1400,
    authorizationCeiling: 1400,
    status: "pending",
    reason: "Extraction confidence 68% is below the 75% threshold; callback time could not be parsed.",
    createdAt: hours(-0.2),
    decidedAt: null,
    decidedByUserId: null,
  },
  {
    id: "n_3",
    tenantId: "t_1",
    loadId: "l_5",
    driverId: "d_6",
    callId: "c_6",
    offeredRate: 1100,
    counterRate: 1150,
    authorizationCeiling: 1139,
    status: "approved",
    reason: "$1,150 exceeded 82% of the $1,390 broker rate ($1,139).",
    createdAt: hours(-25),
    decidedAt: hours(-24),
    decidedByUserId: "u_1",
  },
];

export const agentRuns: AgentRun[] = [
  {
    id: "ar_1",
    tenantId: "t_1",
    loadId: "l_1",
    promptVersion: "dispatch-v0.4.2",
    toolsInvoked: [
      "get_load",
      "find_candidate_drivers",
      "get_authorized_rate",
      "prepare_call",
      "start_outbound_call",
      "save_call_outcome",
      "request_human_approval",
    ],
    latencyMs: 3420,
    result: "escalated",
    error: null,
    startedAt: hours(-3),
  },
  {
    id: "ar_2",
    tenantId: "t_1",
    loadId: "l_2",
    promptVersion: "dispatch-v0.4.2",
    toolsInvoked: [
      "get_load",
      "find_candidate_drivers",
      "get_authorized_rate",
      "prepare_call",
      "start_outbound_call",
      "save_call_outcome",
      "update_load",
      "send_confirmation",
    ],
    latencyMs: 2870,
    result: "success",
    error: null,
    startedAt: hours(-1),
  },
  {
    id: "ar_3",
    tenantId: "t_1",
    loadId: "l_3",
    promptVersion: "dispatch-v0.4.2",
    toolsInvoked: ["get_load", "find_candidate_drivers", "prepare_call", "start_outbound_call", "schedule_followup"],
    latencyMs: 2210,
    result: "success",
    error: null,
    startedAt: hours(-0.5),
  },
  {
    id: "ar_4",
    tenantId: "t_1",
    loadId: "l_6",
    promptVersion: "dispatch-v0.4.2",
    toolsInvoked: ["get_load", "find_candidate_drivers", "prepare_call", "start_outbound_call", "save_call_outcome"],
    latencyMs: 4105,
    result: "escalated",
    error: null,
    startedAt: hours(-0.2),
  },
  {
    id: "ar_5",
    tenantId: "t_1",
    loadId: "l_7",
    promptVersion: "dispatch-v0.4.2",
    toolsInvoked: ["get_load", "calculate_route"],
    latencyMs: 890,
    result: "error",
    error: "calculate_route: upstream routing provider returned 503",
    startedAt: hours(-0.1),
  },
];

export const auditEvents: AuditEvent[] = [
  {
    id: "ae_1",
    tenantId: "t_1",
    actor: "agent:hermes",
    action: "call.placed",
    entityType: "call",
    entityId: "c_1",
    before: null,
    after: { driverId: "d_1", loadId: "l_1", offeredRate: 900 },
    at: hours(-3),
  },
  {
    id: "ae_2",
    tenantId: "t_1",
    actor: "agent:hermes",
    action: "approval.requested",
    entityType: "negotiation",
    entityId: "n_1",
    before: null,
    after: { counterRate: 975, ceiling: 900, decision: "human_approval_required" },
    at: hours(-3),
  },
  {
    id: "ae_3",
    tenantId: "t_1",
    actor: "agent:hermes",
    action: "load.status_changed",
    entityType: "load",
    entityId: "l_1",
    before: { status: "calling" },
    after: { status: "pending_approval" },
    at: hours(-3),
  },
  {
    id: "ae_4",
    tenantId: "t_1",
    actor: "agent:hermes",
    action: "call.outcome_saved",
    entityType: "call",
    entityId: "c_2",
    before: null,
    after: { outcome: "interested", confidence: 0.96 },
    at: hours(-1),
  },
  {
    id: "ae_5",
    tenantId: "t_1",
    actor: "agent:hermes",
    action: "driver.profile_flagged",
    entityType: "driver",
    entityId: "d_2",
    before: { equipment: ["dry_van", "reefer"] },
    after: { equipment: ["dry_van"] },
    at: hours(-2),
  },
  {
    id: "ae_6",
    tenantId: "t_1",
    actor: "user:u_1",
    action: "negotiation.approved",
    entityType: "negotiation",
    entityId: "n_3",
    before: { status: "pending" },
    after: { status: "approved", approvedRate: 1150 },
    at: hours(-24),
  },
  {
    id: "ae_7",
    tenantId: "t_1",
    actor: "user:u_1",
    action: "rules.updated",
    entityType: "rule",
    entityId: "t_1",
    before: { maxRatePercentOfBroker: 85 },
    after: { maxRatePercentOfBroker: 82 },
    at: hours(-30),
  },
  {
    id: "ae_8",
    tenantId: "t_1",
    actor: "system",
    action: "call.blocked",
    entityType: "driver",
    entityId: "d_7",
    before: null,
    after: { reason: "driver_marked_do_not_call" },
    at: hours(-5),
  },
];

// --- Accessors -------------------------------------------------------------
// Narrow read helpers so page components never reach into the arrays directly.
// When this module is replaced by real queries these become the query layer.

export const getLoad = (id: string) => loads.find((l) => l.id === id);
export const getDriver = (id: string) => drivers.find((d) => d.id === id);
export const getCall = (id: string) => calls.find((c) => c.id === id);
export const getTruckForDriver = (driverId: string) => trucks.find((t) => t.driverId === driverId);
export const getCallsForLoad = (loadId: string) => calls.filter((c) => c.loadId === loadId);
export const getCallsForDriver = (driverId: string) => calls.filter((c) => c.driverId === driverId);
export const getNegotiation = (id: string) => negotiations.find((n) => n.id === id);
export const pendingApprovals = () => negotiations.filter((n) => n.status === "pending");
